# Generated by Django 2.2 on 2022-02-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={'verbose_name': 'Detalle de la Compra', 'verbose_name_plural': 'Detalles de las Compras'},
        ),
    ]
