# Generated by Django 2.2 on 2022-02-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_auto_20220207_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasenc',
            old_name='no_factura',
            new_name='nro_factura',
        ),
    ]
