# Generated by Django 2.2 on 2022-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_auto_20220207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='nro_factura',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
