# Generated by Django 2.2.25 on 2022-01-05 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('user_updated', models.IntegerField(blank=True, null=True, verbose_name='Último Modificador')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción de la Categoría', unique=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, height_field=800, null=True, upload_to='inventario/categorias', verbose_name='Imagen', width_field=800)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('user_updated', models.IntegerField(blank=True, null=True, verbose_name='Último Modificador')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción de la Marca', unique=True, verbose_name='Descripción')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('user_updated', models.IntegerField(blank=True, null=True, verbose_name='Último Modificador')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción de la Marca', unique=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, height_field=800, null=True, upload_to='inventario/marcas', verbose_name='Imagen', width_field=800)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('user_updated', models.IntegerField(blank=True, null=True, verbose_name='Último Modificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción de la SubCategoría', verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, height_field=800, null=True, upload_to='inventario/subcategorias', verbose_name='Imagen', width_field=800)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', verbose_name='Categoría')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'SubCategoría',
                'verbose_name_plural': 'SubCategorías',
                'unique_together': {('category', 'description'), ('category', 'name')},
            },
        ),
    ]
