# Generated by Django 3.2.11 on 2022-01-17 20:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220109_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='inventory/categories', verbose_name='Imagen', width_field=800),
        ),
        migrations.AlterField(
            model_name='mark',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='inventory/marks', verbose_name='Imagen', width_field=800),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='inventory/subcategories', verbose_name='Imagen', width_field=800),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
