# Generated by Django 3.2.11 on 2022-01-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220117_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='inventory/subcategories', verbose_name='Imagen', width_field=800),
        ),
    ]
