# Generated by Django 3.2.11 on 2022-01-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='height_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='width_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AddField(
            model_name='mark',
            name='height_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AddField(
            model_name='mark',
            name='width_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='height_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='width_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='inventory/subcategories', verbose_name='Imagen', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='inventory/subcategories', verbose_name='Imagen', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='inventory/subcategories', verbose_name='Imagen', width_field='width_field'),
        ),
    ]
