# Generated by Django 3.2.11 on 2022-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20220118_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='category',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/categories', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/marks', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/subcategories', verbose_name='Imagen'),
        ),
    ]
