# Generated by Django 3.2.11 on 2022-01-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20220118_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='height_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='width_field',
            field=models.PositiveIntegerField(default=800, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='inventory/categories', verbose_name='Imagen', width_field='width_field'),
        ),
    ]
