# Generated by Django 3.2.11 on 2022-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220120_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='height_field',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='width_field',
            field=models.PositiveIntegerField(),
        ),
    ]
