# Generated by Django 3.2.11 on 2022-01-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20220121_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/categories', verbose_name='Imagen'),
        ),
    ]
