# Generated by Django 2.2.13 on 2021-12-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'descripcion')},
        ),
    ]
