# Generated by Django 2.2 on 2022-04-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_compras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioc',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='preciov',
        ),
    ]
